# Generated by Django 3.0.2 on 2020-01-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on with the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on with the object was last modified.', verbose_name='modified_at')),
                ('name', models.CharField(max_length=140, verbose_name='cirlce name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('about', models.CharField(max_length=255, verbose_name='cirlce description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='cirlce/pictures')),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified circle are also know as official communities.', verbose_name='verified cirle')),
                ('is_public', models.BooleanField(default=False, help_text='Public circles are listed in the main page so everyone know about their existence.')),
                ('is_limited', models.BooleanField(default=False, help_text='Limited cirlces can group to a fixed number of members.')),
                ('members_limit', models.PositiveIntegerField(default=0, help_text='If circle is Limited, this will be the limit on the number of members.')),
            ],
            options={
                'ordering': ('-rides_taken', '-rides_offered'),
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
