# Generated by Django 2.2.1 on 2019-08-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20190607_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only active users are allowed to interact in the circle.', verbose_name='active status'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_admin',
            field=models.BooleanField(default=False, help_text="Circle admisn can update the circle's data and manage its members.", verbose_name='circle admin'),
        ),
    ]
